name: build
on: [ push ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync submodules
        run: |
          git submodule init
          git submodule update
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mono-devel
      - name: generate makefiles
        run: |
          chmod +x linux-genprojects.sh
          ./linux-genprojects.sh
      - name: build
        run: |
          make -j 8 config=release