name: build
on: [ push ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync submodules
        run: |
          git submodule init
          git submodule update
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel
      - name: generate makefiles
        run: |
          ./linux-genprojects.sh
      - name: build
        run: |
          make -j 8 config=release
      - name: package binaries
        run: |
          ./package-unix.sh build-nightly Release linux x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-ubuntu
          path: fe_engine.tar.gz
  windows-build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2
      - name: sync submodules
        shell: cmd
        run: |
          git submodule init
          git submodule update
      - name: generate build files
        shell: cmd
        run: |
          windows-genprojects.bat
      - name: build
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" fe_engine.sln -p:Configuration=Release -m
      - name: package binaries
        shell: bash
        run: |
          ./package-unix.sh build-nightly Release windows x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-windows
          path: fe_engine.tar.gz
  macosx-build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync submodules
        run: |
          git submodule init
          git submodule update
      - name: install dependencies
        run: |
          brew install --force mono
      - name: generate makefiles
        run: |
          ./mac-genprojects.sh
      - name: build
        run: |
          make -j 8 config=release
      - name: package binaries
        run: |
          ./package-unix.sh build-nightly Release macosx x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-macosx
          path: fe_engine.tar.gz
