name: build
on: [ push ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sync submodules
        run: |
          git submodule init
          git submodule update
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel zip
      - name: generate makefiles
        run: |
          chmod +x linux-genprojects.sh
          ./linux-genprojects.sh
      - name: build
        run: |
          make -j 8 config=release
      - name: package binaries
        run: |
          chmod +x package-unix.sh
          ./package-unix.sh pkg Release linux x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-ubuntu
          path: fe_engine.tar.gz