name: build
on: [ push ]
jobs:
  windows-build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install mono
        shell: cmd
        run: |
          curl -L https://download.mono-project.com/archive/6.12.0/windows-installer/mono-6.12.0.107-x64-0.msi -o mono.msi
          msiexec /i mono.msi /quiet
      - name: generate build files
        shell: cmd
        run: |
          vendor\binaries\windows\premake5 vs2019
      - name: build
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" fe_engine.sln -p:Configuration=Release -m
      - name: create artifact
        shell: bash
        run: |
          chmod +x create-artifact.sh
          ./create-artifact.sh FEEngine Release windows x86_64 FEEngine
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-windows
          path: FEEngine.tar.gz
