name: macosx-native
on: [ push ]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install mono
        run: |
          curl -L https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.122.macos10.xamarin.universal.pkg -o mono.pkg
          sudo installer -pkg mono.pkg -target /
      - name: generate makefiles
        run: |
          ./mac-genprojects.sh
      - name: build
        run: |
          make -j 8 config=release
      - name: package binaries
        run: |
          ./package-unix.sh build-nightly Release macosx x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-macosx
          path: fe_engine.tar.gz
