name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            5.0.x
      - name: build
        shell: bash
        run: |
          dotnet restore
          dotnet build -c Release
      - name: test
        shell: bash
        run: |
          dotnet test -c Release