name: windows-native
on: [ push ]
jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: generate build files
        shell: cmd
        run: |
          windows-genprojects.bat
      - name: build
        shell: cmd
        run: |
          "%MSBUILD_PATH%\MSBuild.exe" fe_engine.sln -p:Configuration=Release -m
      - name: package binaries
        shell: bash
        run: |
          ./package-unix.sh build-nightly Release windows x86_64 fe_engine.tar.gz
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-windows
          path: fe_engine.tar.gz
